### ISSUE TITLE
Problem bei der Registrierung

### ISSUE THREAD

**Issue by benediktr** [benediktr/Quiz-Webseite#3]
Bei der Einfügung  der Userid in die user_scores Datenbank tritt ein Fehler auf.
Außerdem wird nichts in die Datenbank geschrieben.

**Comment by kellerlu** [comment]
Problem gelöst. Da die Scores am Anfang so oder so auf 0 müssen, muss man auch bei der Registrierung nichts übergeben.
Falls man was übergeben muss bzw. einen Wert setzen möchte, dann ist dies nun auch möglich.
